### ISSUE TITLE
Object cloning does not perform deep clones

### ISSUE THREAD

**Issue by ToxicBakery** [MasDennis/Rajawali#1147]
As discussed in #1137 object cloning does not perform deep copies of the object so sub objects are not included in the clone. It seems, to me, that the default behavior of cloning should perform a deep copy and alternately (overloaded) provide a shallow copy.

**Comment by jwoolston** [comment]
@exean implemented this in 5c4baa42dc5229f8e5d4cf76eec4518b754006b8. We still need to decide if we should provide an option for disabling deep cloning.

**Comment by jwoolston** [comment]
Rather, we will provide shallow cloning, but need to implement it.

**Comment by jwoolston** [comment]
Went to implement this and realized the option was already added to the API. Closing as resolved.
