### ISSUE TITLE
Queue up task for next  onDrawFrame

### ISSUE THREAD

**Issue by chodge** [MasDennis/Rajawali#1247]
To start off, I'm pretty new to OpenGL, so I might be doing something terribly wrong...

I have an app that allows users to manipulate a single Model: rotate, pan, zoom...

In the pinch/zoom, I'd like to ensure that the point on the model in the center of the "pinch" stays in that same screen location (looks like #216 was doing the same thing). Here's what I'm thinking I'll have to do:
1. Get the world coordinates for the screen coordinates of the center of the pinch, with a z of the nearest point of the model.
2. Scale the model straight in/out
3. Find out what the new world coordinates are for that screen position.
4. Translate the model so it's back where it should be.

Alternately, if I could know how much it needed to move, I could make step 2 a scale + translate.

I can certainly post code if it helps, but does that flow conceptually make sense? If so, how should I go about it? I'm using the Master branch of the code.

Two other questions for clarification while I'm at it:
1. For getting the world coordinates from screen coordinates, I'm using https://github.com/MasDennis/Rajawali/issues/81#issuecomment-6993686. Is there a better way? My renderer's unProject() always returns null.
2. Is there a canonical "manipulate a model" example or tutorial out there? The Android SDK has a "Touch Rotate" example using a cube, but it's not a great implementation.

**Comment by jwoolston** [comment]
@chodge See a37ec1ba72528f8854abdf03fb7b3418161ff036. As of this commit, there is a callback system to allow precisely what you are asking for.
