### ISSUE TITLE
Android Runtime (ART) issues.

### ISSUE THREAD

**Issue by dcerisano** [MasDennis/Rajawali#1255]
Just upgraded my Nexus 5 to Kitkat and switched from Dalvik the the experimental Android Runtime (ART).

Noticed a couple of issues while running my big Rajawali application (multithreaded, custom shaders, etc):
1) Slower (much). 
2) Custom fonts not working.

Just looking into it now, but I have a feeling ART is really "not ready for primetime." It also dropped my cellular connection (not running ART anymore!)

I doubt the problems are coming from Rajawali, but just a heads-up that workarounds may be required to overcome shake-in issues with ART.

**Comment by jwoolston** [comment]
Closing as stale/no longer relevant since ART is the default runtime.
