### ISSUE TITLE
animate rigged model according to given commands

### ISSUE THREAD

**Issue by aeroxr1** [MasDennis/Rajawali#1260]
Hello to everyone :)
I know that Rajawali can imports rigged models, 
https://github.com/MasDennis/Rajawali/wiki/Tutorial-29-Skeletal-Animation 
But I'm trying to animate a human's rigged model for an Android Application ( Real-time Motion Capture ). 
Is possible to do this using rajwali ?
Something like this https://www.youtube.com/watch?v=NYT-nx533nM

**Comment by jwoolston** [comment]
Closing as resolved.
