### ISSUE TITLE
How to rotate camera by data from gyroscope

### ISSUE THREAD

**Issue by billda007** [MasDennis/Rajawali#1307]
Hi, I am trying to make an example app that shows some basic model (cube, sphere) and rotate camera that is looking at that object with angles from gyroscope. My problem is that when I call something like this 
 @Override
    protected void render(double deltaTime) {
        super.render(deltaTime);
        if (rotation != null) {
          getCurrentCamera().setRotation(rotation[0], rotation[1]  rotation[2]);
        }
    }

The model is a little shaking but no rotation is performed. When I use rotation vector and compute rotation matrix and use it like this:

 @Override
    protected void render(double deltaTime) {
        super.render(deltaTime);
        if (rotationMatrix != null) {
            getCurrentCamera().setRotationMatrix(getRotationMatrix(rotationMatrix));
        }
    }

only model is rotating and not the camera. What I am doing wrong? Thanks

**Comment by jwoolston** [comment]
@billda007 I am closing this issue as stale. If you are still having trouble please reply and we will re-open it and chime in.

**Comment by huylv177** [comment]
@davidbilik Did you finish this problem? i have the same problem but i cant implement it :(

**Comment by sunjinbo** [comment]
mayb this post is what you want. 
[post](https://stackoverflow.com/questions/35579964/rajawali-rotating-camera-with-sensor-type-rotation-vector-strange-behavior)
