### ISSUE TITLE
Rajawali Classes missing

### ISSUE THREAD

**Issue by abhijitsrivastava** [MasDennis/Rajawali#1309]
Hi,

I am trying to implement the RajawaliTutorial1 application through the following documentation "https://github.com/MasDennis/Rajawali/wiki/Tutorial-01----Basic-Setup-&-a-Sphere".

And on the first step I found that some of the classes are missing from the rajawali library like 
1) rajawali.BaseObject3D
2) DiffuseMaterial

I don't how many others are also missing in it.

will you please tell me how can I get the complete library of rajawali or is there any thing wrong I am doing??

**Comment by jwoolston** [comment]
Closing as resolved. Thanks @abhishekBansal.
