### ISSUE TITLE
Two RajawaliRenderer instances, texture problem

### ISSUE THREAD

**Issue by jhavelik** [MasDennis/Rajawali#1310]
Hi everyone,
in my app i use RajawaliVuforiaRenderer with activity A, and on some action i create new activity B with attached (using beginTransaction(), add(), comit()) RawajaliFragment where is rotating model (kind of preview of model). Activity A is not destroyed.
In activity B i change some parameters, finish this activity and move back to activity A, where i create simple plane model with texture by changed parameters (different text on texture bitmap). But texture on plane model is not displayed (only like black material without texture).
When i dont attach RawajaliFragment to activity B everything works fine. Any thoughts why this not working? Can I have mutliple RajawaliRenderers in my app runnig simultaneously. 
Thanks for answers....

**Comment by jwoolston** [comment]
The texture manager is a singleton class. When you create another `RajawaliRenderer` you are essentially giving the texture manager a new EGL context, causing it to loose all of its textures from the first context. You will need to re-initialize the scene in this case. The better solution is to use a single `RajawaliRenderer` and switch between two `RajawaliScene` classes. It was intended for exactly this purpose.

**Comment by paulpv** [comment]
@jwoolston But what if the intention is to have separate renderers showing potentially entirely different things?
Would it be reasonable to have multiple renderers then?

A problem occurs when this happens:

1. An instance of Renderer1 is created, which eventually calls TextManager.registerRenderer and MaterialManager.registerRenderer, setting the current renderer (mRenderer) to Renderer1.
Renderer1.initScene adds Texture1 which queues a Task to add the texture to the TextureManager.
2. Before the Task to add Texture1 runs, an instance of Renderer2 is created, which eventually calls TextManager.registerRenderer and MaterialManager.registerRenderer, setting the current renderer to Renderer2.
Renderer2.initScene adds Texture2 which queues a Task to add the texture to the TextureManager.
3. The queued Tasks to add Texture1 and Texture2 run; TextureManager only adds the textures to the active renderer, Renderer2. Renderer1 is left without any textures, and draws objects in black.
