### ISSUE TITLE
Need to perform animations using .md2 similar to that of rajawali's ogre 

### ISSUE THREAD

**Issue by ernchawla** [MasDennis/Rajawali#1323]
When I am exporting my model from blender(in .md2) it's parsing perfectly (without the texture(I don't know how to add texture for .md2 file))in my application but when I am doing the same from Max3D the model is not getting parsed into the application with logcat error NO package identifier when getting value for resources 0x00000000...Is it the issue that I am exporting from Max or something else.
Plus two more queries,how they are adding the texture to ogro ??I followed the tutorial but couldn't find the code where they are adding the texture to it.
And lastly, how they are playing animation like this mOgre.playAnimation("wave")...Is it the animations are first saved to the file with their respective name ("wave","death"...)or there is some different science behind it. Please guide me.

**Comment by jwoolston** [comment]
Closing as resolved. Thanks @dcerisano.
