### ISSUE TITLE
Animation.mIsFirstStart should be initialized as true

### ISSUE THREAD

**Issue by flankechen** [MasDennis/Rajawali#1326]
I use following code to play a small scale up animation.

//                      object have been set, and add to the scene, and set a scale 1.0.

			anim = new ScaleAnimation3D(new Vector3(1.3f,1.3f,1f));
			anim.setInterpolator(new LinearInterpolator());
			anim.setDurationMilliseconds(2000);
			
//			anim.setRepeatMode(RepeatMode.RESTART);
//			anim.setRepeatCount(2);
			anim.setTransformable3D(Object));
			getCurrentScene().registerAnimation(anim);

			anim.play();

however, I find the object scales up from 0 to 1.3 rather than from 1.0 to 1.3. 
I trace the code and find that 
if (isFirstStart())
    mFromScale.setAll(mTransformable3D.getScale());
in Rajawali\trunk\src\rajawali\animation\ScaleAnimation3D.java  is never called! mFromScale is always (0.0, 0.0, 0.0)!!

in Rajawali\trunk\src\rajawali\animation\Animation.java,
private boolean mIsFirstStart should be initialized as true in the beginning. and set to false when evenstart(). otherwise, is false at the very beginning. and 
public boolean isFirstStart() {
		return mIsFirstStart;
	} 
will always return false;

BTW, I initialized mIsFirstStart as true and gets the right behavior(scale from 1.0 to 1.3).

**Comment by jwoolston** [comment]
Closing as fixed via #1327
