### ISSUE TITLE
When issueing a Scene.clearChildren task an exception is thrown

### ISSUE THREAD

**Issue by sergedesmedt** [MasDennis/Rajawali#1338]
In the latest code, when processing the REMOVE_ALL task created by a call to Scene.clearChildren an exception is thrown.

When removing a child one by one it works.

I've been digging into the code and come to the following conclusion:

```java
	public boolean clearChildren() {
		return queueClearTask(AFrameTask.TYPE.OBJECT3D);
	}

	protected boolean queueClearTask(AFrameTask.TYPE type) {
		GroupTask task = new GroupTask(type);
		task.setTask(AFrameTask.TASK.REMOVE_ALL);
		task.setIndex(AFrameTask.UNUSED_INDEX);
		return addTaskToQueue(task);
	}

	private void handleRemoveAllTask(AFrameTask task) {
		GroupTask group = (GroupTask) task;
		AFrameTask.TYPE type = group.getFrameTaskType();
		boolean clear = false;
		AFrameTask[] tasks = null;
		int i = 0, j = 0;
		// Not sure what you are trying to do here
		if (type == null) {
			clear = true;
		} else {
			// The collection has not been set, resulting in an ArgumentNullException
			tasks = (AFrameTask[]) group.getCollection().toArray();
			type = tasks[0].getFrameTaskType();
			j = tasks.length;
		}
```

I'm not sure on how to fix it, as it is unclear to me what you're trying to achive with the "if (type == null)" check

**Comment by sergedesmedt** [comment]
Just to make clear as it may not ave been apparent in the above:
I added commentlines in the copy-pasted code where the exception is thrown.

private void handleRemoveAllTask(AFrameTask task) {
    // More code here
    // Not sure what you are trying to do here
    if (type == null) {
        clear = true;
    } else {
        // The collection has not been set, resulting in an ArgumentNullException
        tasks = (AFrameTask[]) group.getCollection().toArray();
        type = tasks[0].getFrameTaskType();
        j = tasks.length;
    }

The exception is thrown on the line "tasks = (AFrameTask[]) group.getCollection().toArray();"
The getCollection() method returns null because it has not been set, see the "clearChildren()" and "queueClearTask(AFrameTask.TYPE type)" methods

**Comment by jwoolston** [comment]
This is an oversight from copy and paste errors, just like the other task queue bug (#1339) you found is. I will fix tonight or you can send a pull request.
