### ISSUE TITLE
mTextureManager.addTexture necessary?

### ISSUE THREAD

**Issue by ChrisMCMine** [MasDennis/Rajawali#1341]
I've read the wiki and looked through various samples but I'm still not sure when I should use
```
material.addTexture(texture);
```
and when 
```
material.addTexture(mTextureManager.addTexture(texture));
```

**Comment by mlatu** [comment]
Material's `addTexture` accepts `TextureInfo`. `TextureManager`'s `addTexture` accepts `Bitmap` (among others). 

If you plan to reuse your texture you can:
```
TextureInfo textureInfo = getTextureManager().addTexture(bitmap);
material_one.addTexture(textureInfo);
material_two.addTexture(textureInfo);
```
But if you use a texture for just one material you can shorten it to one line like in your 2nd example.

**Comment by jwoolston** [comment]
@mlatu Thankyou, perfect explanation. Closing as resolved.
