### ISSUE TITLE
Java to iOS migration path?

### ISSUE THREAD

**Issue by dcerisano** [MasDennis/Rajawali#1342]
J2OBJC is a new migrator from Google that ports all non-UI android java code to Objective C.
http://www.androidcentral.com/google-develops-tool-translate-java-ios-friendly-objective-c-code

Rajawali is primarily an OpenGL framework which makes it a candidate for migration.

Has anyone tried this? It is pretty darned exciting. I know much of the android specific (UI fragments) code won't port, but all of the opengl specific (scene graph) stuff should. 

Lots of people are making pure scene graph apps with Rajawali. The Rajawali VR apps come to mind. There is already a port of Google's Cardboard VRToolkit to iOS.
https://github.com/equinox2k/CardboardVR-iOS

Rajawali is an excellent complement to Cardboard which has no such OpenGL framework support. You can't use any kind of touch UI components in VR mode anyway.

Fanboy alert: Java is a friendlier language than Klingon (Objective C).

**Comment by jwoolston** [comment]
Currently none of the devs perform or have any interest in performing iOS development. I don't forsee us objecting to the conversion, but we will not be able to perform it or support it. Any effort will have to be from other developers.
