### ISSUE TITLE
How to optimize MD5 animations if more objects in scene

### ISSUE THREAD

**Issue by mukulabdagiri** [MasDennis/Rajawali#1343]
Hello,

I am using MD5 animations for my Live Wallpapers. I exported the mesh and anim using MD5 exporter in 3DS Max. The animations work fine, but if i add more objects (>3), the animation stops for a second and then resumes. This happens every 3-4 seconds. Each object is approx 2000 polygons and around 40 joints with keyframe animations. Is there a way i can optimise MD5 animations to get rid of this momentary lag?

Thanks,
Mukul

**Comment by dcerisano** [comment]
You could try spawning separate threads for each animation.
2000 polys is rather high. You could try decimating the mesh in 3DS to under 1000 polys.

**Comment by jwoolston** [comment]
@mukulabdagiri I agree with @dcerisano, decimation is  a good place to start. The animation system in Rajawali can be managed by the GL thread for simple cases, but in more complex cases, his suggestion of additional threads is also correct. Closing as stale/resolved. Further info on the matter can be posted here and we will re-open the question.
