### ISSUE TITLE
Load textures from .mtl with LoaderOBJ

### ISSUE THREAD

**Issue by Metalride** [MasDennis/Rajawali#1344]
Hello, i´m new with Rajawali and i don´t know how to load a file .obj with a texture file. Can you help me?
Thanks

**Comment by jwoolston** [comment]
If using the `v0.9` tag, see https://github.com/MasDennis/Rajawali/wiki/Tutorial-17-Importing-.Obj-Files. If using `master`, most of that will still be valid, though the recommended path now is to use the AWD format. The tutorial here: https://github.com/MasDennis/Rajawali/wiki/Tutorial:-AWD-File-Parsing explains how to easily convert from OBJ models to AWD.
