### ISSUE TITLE
Validate LINT configuration

### ISSUE THREAD

**Issue by jwoolston** [MasDennis/Rajawali#1359]
As Lint and AS have evolved, along with the library, we have never actually gone through the library to clean the lint errors, and frankly, most of them are worth following, especially in the context of Android best practices. We need to update the lint configuration, and then systematically go through the library cleaning any errors.

**Comment by ToxicBakery** [comment]
Lint check all the things!

**Comment by jwoolston** [comment]
@ToxicBakery I come back to development after so long and you dont even welcome me with a meme? I am hurt sir!

**Comment by ToxicBakery** [comment]
![tumblr_mimyw3bcsm1s3o5b8o3_250_zpsdeb4a3b0](https://cloud.githubusercontent.com/assets/1614281/6596762/b87fea70-c7cd-11e4-803c-e09c01e55155.gif)

**Comment by jwoolston** [comment]
Much better :smiley_cat:
