### ISSUE TITLE
WIP: Post Processing Effects Reloaded

### ISSUE THREAD

**Issue by AndrewJo** [MasDennis/Rajawali#648]
With @jwoolston's scenegraph code starting to mature, I want to put aside RenderScript for a bit and work on overhauling the post processing effects because this is something that @jwoolston mentioned could effect the architectural design of his scenegraph framework.

## Game Plan
Essentially, I'm thinking it will go down a similar architectural design as EffectComposer class in THREE.js. Big difference would be instead of creating a new EffectComposer and passing in the reference to the renderer class, we would essentially add EffectComposer to the renderer. You can have multiple EffectComposer classes in the renderer to blend two post processing effects.

## API
This can change but for now, it'll be similar to method names from THREE.js. RajawaliRenderer will maintain a list of EffectComposer classes.

### EffectComposer class
Responsible for handling multiple rendering passes.
* addPass(IPass pass)
* removePass(IPass pass)

### APass abstract class
Contains configuration information about the rendering pass (e.g. texture size, whether to render color buffer or depth buffer).

**RenderPass class (inherits from APass)**
This renders the given scene in a rendering pass. Constructors at the very least should take in a reference to the scene instance.

**ShaderPass class (inherits from APass)**
Write and assign a custom shader to perform post processing operations on the texture. This is essentially applying a filter in the previous PostProcessingRenderer framework.

## Example
* Bloom/glow
  1. Set up EffectComposer instance for the glowmap
  2. Set up scene with non-emissive objects and another scene with all the emissive objects.
  3. Set up RenderPass with colorwrites disabled for the non-emissive objects
  4. Set up RenderPass with colorwrites enabled for the scene with emissive objects
  5. Set up ShaderPass with horizontal blur
  6. Set up ShaderPass with vertical blur
  7. Set up EffectComposer instance for the entire scene
  8. Set up RenderPass with the entire scene (both emissive and non-emissive)
  9. Set up ShaderPass with screen (or additive) blend (glowmap + rendered scene)

What do you guys think? I want to discuss the implementation design before I start typing away at the code.

**EDIT :** I forgot to add but the RajawaliRenderer will render the scene normally to the screen if the EffectComposer list is empty. In otherwords, it will iterate and call render method on the scenes. If not, it will iterate through EffectComposer list and call the render method of the EffectComposer to render the scenes.

**Comment by jwoolston** [comment]
As of 09214d252b99a0885292d0fc46bed3ff1b702b94 it appears this is complete. @MasDennis I am closing this for now, please re-open if you feel differently.
